### ISSUE TITLE
Gems not running on iframes

### ISSUE THREAD

**Issue by padmavemulapati** [dequelabs/axe-core-gems#164]
Steps to reproduce:
1. Pulled the axe-core-gems code(axe-core v4.1.0)
2. bundles installed
3. navigated to axe-core-cucumber/e2e/capybara
for the test file: "http://qateam.dequecloud.com/attest/api/test.html"
Its giving the results excluding "iframe" related issues.
Actual:
5 types issues found:
1. aria-allowed-attr
2.autocomplete-valid
3. color-contrast
4. heading-order
5. label

Expected:
1. aria-allowed-attr
2.autocomplete-valid
3. color-contrast
4. heading-order
5. label
6. dl-item (iframe related ids are there)
7. image-alt (iframe related ids are there)
Actual:
[issue-1.txt](https://github.com/dequelabs/axe-core-gems/files/5567534/issue-1.txt)
Expected:
[expectedForissue-1.txt](https://github.com/dequelabs/axe-core-gems/files/5567536/expectedForissue-1.txt)

Note: same issue seeing with "rspec" too

**Comment by padmavemulapati** [comment]
After updating the current version its working fine.

**Comment by SantoshDeque** [comment]
Verified this issue in release branch(release-2020-05-17) and iframes related violations are being displayed now. PFA gif file
![20210518_201813](https://user-images.githubusercontent.com/45222788/118673323-8714a300-b816-11eb-86df-ea2a1375f4ca.gif)

**Comment by michael-siek** [comment]
closing on docs required
