### ISSUE TITLE
Gems not considering multiple ruleIds checking 

### ISSUE THREAD

**Issue by padmavemulapati** [dequelabs/axe-core-gems#165]
Steps to reproduce:

1.Pulled the axe-core-gems code(axe-core v4.1.0)
2. bundles installed
3. navigated to axe-core-cucumber/e2e/watir (also issue with axe-core-rspec/e2e/capybara)
for the test file: "http://qateam.dequecloud.com/attest/api/test.html"
When I tried to analyse the page for specific rules, 
` Given I am a visitor `
   ` When I visit "http://qateam.dequecloud.com/attest/api/test.html" `
 ` Scenario: Test whole page (known to be inaccessible, should fail)`
  `Then the page should be axe clean checking: aria-allowed-attr, label `

before :each do
    visit "http://qateam.dequecloud.com/attest/api/test.html"
  end

  it "is known to be inaccessible, should fail" do
    expect(page).to be_axe_clean.checking :label
  end
(here it need to correct the readME file too  for command correction )
Actual:
Its not checking the specific rules, but checking entire results.

**Comment by jeeyyy** [comment]
This is working as expected. Closing issue.
