### ISSUE TITLE
Capybara driver opens multiple windows instances

### ISSUE THREAD

**Issue by padmavemulapati** [dequelabs/axe-core-gems#166]
Steps to reproduce:

1.Pulled the axe-core-gems code(axe-core v4.1.0)
2. bundles installed
3. navigated to axe-core-cucumber/e2e/cucumber
for the test file: "http://qateam.dequecloud.com/attest/api/test.html"
When I tried to analyse the page  looks like `analyze()` is running on empty page(though it has launched the correct page first, later empty screen is shown).. so it is not giving voilations for empty page.
Test feature:
`Given I am a visitor`
`When I visit "http://qateam.dequecloud.com/attest/api/test.html"`
`Scenario: Test whole page (known to be inaccessible, should fail)`
`Then the page should be axe clean `
![20201119_151907](https://user-images.githubusercontent.com/47409579/99684226-34e10800-2aa7-11eb-80fa-ace9d9bbc457.gif)

**Comment by jeeyyy** [comment]
Although the results are correct, need to debug why multiple browser instances are spun up.

**Comment by dequejenn** [comment]
@padmavemulapati - can you retest and see if this is still an issue?

**Comment by padmavemulapati** [comment]
Verified with the latest QA-build (4.8.1.pre.55671fe) - not seeing any issue.



https://github.com/dequelabs/axe-core-gems/assets/47409579/7d3696c1-18c6-4815-8503-1f70436ac700

## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Product**                | _axe-core-gems_ |
|**Version** | _4.8.1.pre.55671fe_ |
| **OS-Details**      | _MAC- Intel Core i7 - 11.6.8 && Windows 11 _ |
|**BrowserDetails**|_Chrome Version 120.0.6099.129   & Firefox 121.0_|
