### ISSUE TITLE
Are there plans for axe-minitest?

### ISSUE THREAD

**Issue by onesneakymofo** [dequelabs/axe-core-gems#170]
Hello,

We have to use Minitest when writing system tests and Rspec when writing accessibility tests (using axe).  We're repeating our tests in both a lot of the times.  I was wondering if there were any plans to have an `axe-minitest` so we can move our tests over to Minitest?

Thanks.

**Comment by hschne** [comment]
I'd be curious what kind of support you'd be looking for? The present RSpec support doesn't do much other than expose `Axe::Matchers::BeAxeClean` to Rspec, and you could write a custom assertion in Minitest that uses that. 

Assuming you have some Capybara test you could do:

```ruby
require 'require 'axe/matchers/be_axe_clean'

class AccessibilityTest < ActionDispatch::SystemTestCase
  driven_by :selenium, using: :headless_chrome
  test 'landing page should not have accessibility issues' do
    visit '/'

    matcher = Axe::Matchers::BeAxeClean.new.impact(:critical)
    assert_accessible(page, matcher)
  end
  
  # Move this to for example your test_helper 
  def assert_accessible(page, matcher)
    assert(matcher.passed?(page), matcher.failure_message_when_negated)
  end
```

The above should work as long as you have `axe-core-api` added to your Gemfile.

**Comment by ryanfb** [comment]
Here's an updated `assert_accessible` method which can be used with `axe-core-api` as of this writing (4.2.1):

```ruby
def assert_accessible(page, matcher = Axe::Matchers::BeAxeClean.new.according_to(:wcag21aa, 'best-practice'))
  audit_result = matcher.audit(page)
  assert(audit_result.passed?, audit_result.failure_message)
end
```

**Comment by dequejenn** [comment]
See workaround above
