### ISSUE TITLE
Question: Is there a reason to include capybara, selenium-webdriver and watir in axe-core-api?

### ISSUE THREAD

**Issue by abrom** [dequelabs/axe-core-gems#176]
Firstly, thank you for the great tool.

I'm looking to update from `axe-matchers` to the newer `axe-core-...` libraries but noticed that the `axe-core-api` is installing the `capybara`, `selenium-webdriver` and `watir` gems. Is there a reason they are explicitly referenced/installed there? I couldn't find any direct references to those gems (being loaded) in the `axe-core-api`. I see that they are referenced in the specs, however it would seem more appropriate to include them in the `Gemfile`?

**Comment by abrom** [comment]
Any thoughts about this @michael-siek or @AdnoC  ? 

I'd be happy to put together a PR to address this

**Comment by AdnoC** [comment]
They shouldn't be installed if you just install api. A PR would be welcome.

**Comment by AdnoC** [comment]
Also, sorry for the late response.
