### ISSUE TITLE
Release v4.2

### ISSUE THREAD

**Issue by michael-siek** [dequelabs/axe-core-gems#180]
When upgrading to use axe-core@4.2 we will need to add the ability to configure [frame origin](https://github.com/dequelabs/axe-core/blob/develop/doc/API.md#allowedorigins)

**Comment by padmavemulapati** [comment]
QAed axe-core-gems-4.2.0 with axe-core-4.2.0,
observed couple of issues:
https://github.com/dequelabs/axe-core-gems/issues/183
https://github.com/dequelabs/axe-core-gems/issues/164
As both got fixed  and verified. 
So we are good with this current build, can go for release.

**Comment by michael-siek** [comment]
Closing no docs required
