### ISSUE TITLE
capabara: giving wrong results

### ISSUE THREAD

**Issue by padmavemulapati** [dequelabs/axe-core-gems#183]
Steps to reproduce:
1. Bundles installed from release branch axe-core-gems
2. Verified the axe-core version , 4.2.0
3. On `bundle exec cucumber` in `capabara` driver:
violations list is not expected. 

``` js- testfile
@javascript
Feature: Example using default Capybara setup
  Default driver is :rack_test, uses :selenium by default for any test tagged
  with @javascript.

  Background:
    Given I am a visitor
    When I visit "http://qateam.dequecloud.com/attest/api/test.html"

  Scenario: Test whole page (known to be inaccessible, should fail)
    Then the page should be axe clean according to: wcag2a
```
***********************************
Output:
******************
bundle exec cucumber
*** WARNING: You must use ANSICON 1.31 or higher (https://github.com/adoxa/ansicon/) to get coloured output on Windows
@javascript
Feature: Example using default Capybara setup
  Default driver is :rack_test, uses :selenium by default for any test tagged
  with @javascript.

  Background:                                                        # features/a11y.feature:6
    Given I am a visitor                                             # features/step_definitions/steps.rb:1
    When I visit "http://qateam.dequecloud.com/attest/api/test.html" # features/step_definitions/steps.rb:4

  Scenario: Test whole page (known to be inaccessible, should fail) # features/a11y.feature:10
    Then the page should be axe clean according to: wcag2a          # C:/Users/DQ_Santosh/Documents/Releases/Axe-core-4.2/axe-core-gems-release-2020-05-06/axe-core-gems-release-2020-05-06/packages/axe-core-cucumber/lib/axe-cucumber-steps.rb:3

      Found 2 accessibility violations:

      1) document-title: Documents must have <title> element to aid in navigation (serious)
          https://dequeuniversity.com/rules/axe/4.2/document-title?application=axeAPI
          The following 1 node violate this rule:

              Selector: html
              HTML: <html><head></head><body></body></html>
              Fix any of the following:
              - Document does not have a non-empty <title> element

      2) html-has-lang: <html> element must have a lang attribute (serious)
          https://dequeuniversity.com/rules/axe/4.2/html-has-lang?application=axeAPI
          The following 1 node violate this rule:

              Selector: html
              HTML: <html><head></head><body></body></html>
              Fix any of the following:
              - The <html> element does not have a lang attribute

      Invocation: axe.run({"runOnly":{"type":"tag","values":["wcag2a"]}}, callback); (RuntimeError)
      C:/Users/DQ_user/Documents/Releases/Axe-core-4.2/axe-core-gems-release-2020-05-06/axe-core-gems-release-2020-05-06/packages/axe-core-api/lib/axe/expectation.rb:4:in `assert'
      C:/Users/DQ_user/Documents/Releases/Axe-core-4.2/axe-core-gems-release-2020-05-06/axe-core-gems-release-2020-05-06/packages/axe-core-cucumber/lib/axe-cucumber.rb:65:in `assert_accessibility'
      features/a11y.feature:13:in `the page should be axe clean according to: wcag2a'

Failing Scenarios:
cucumber features/a11y.feature:10 # Scenario: Test whole page (known to be inaccessible, should fail)

1 scenario (1 failed)
3 steps (1 failed, 2 passed)
0m15.368s
````
Expected: 
```
 Violation of "aria-allowed-attr" with 1 occurrences!
    Ensures ARIA attributes are allowed for an element's role. Correct invalid elements at:
     - #wcag2a-fail > a[href="\#"][role="button"]
    For details, see: https://dequeuniversity.com/rules/axe/4.2/aria-allowed-attr

    Violation of "label" with 1 occurrences!
    Ensures every form element has a label. Correct invalid elements at:
     - input[name="lastname"]
    For details, see: https://dequeuniversity.com/rules/axe/4.2/label

2 Accessibility issues detected.
````

and also for the scenario
```
Background:
    Given I am a visitor
    When I visit "http://qateam.dequecloud.com/attest/api/test.html"

  Scenario: Test whole page (known to be inaccessible, should fail)
    Then the page should be axe clean
```

output
```
bundle exec cucumber
*** WARNING: You must use ANSICON 1.31 or higher (https://github.com/adoxa/ansicon/) to get coloured output on Windows
@javascript
Feature: Example using default Capybara setup
  Default driver is :rack_test, uses :selenium by default for any test tagged
  with @javascript.

  Background:                                                        # features/a11y.feature:6
    Given I am a visitor                                             # features/step_definitions/steps.rb:1
    When I visit "http://qateam.dequecloud.com/attest/api/test.html" # features/step_definitions/steps.rb:4

  Scenario: Test whole page (known to be inaccessible, should fail) # features/a11y.feature:10
    Then the page should be axe clean                               # C:/Users/DQ_Santosh/Documents/Releases/Axe-core-4.2/axe-core-gems-release-2020-05-06/axe-core-gems-release-2020-05-06/packages/axe-core-cucumber/lib/axe-cucumber-steps.rb:3

      Found 4 accessibility violations:

      1) document-title: Documents must have <title> element to aid in navigation (serious)
          https://dequeuniversity.com/rules/axe/4.2/document-title?application=axeAPI
          The following 1 node violate this rule:

              Selector: html
              HTML: <html><head></head><body></body></html>
              Fix any of the following:
              - Document does not have a non-empty <title> element

      2) html-has-lang: <html> element must have a lang attribute (serious)
          https://dequeuniversity.com/rules/axe/4.2/html-has-lang?application=axeAPI
          The following 1 node violate this rule:

              Selector: html
              HTML: <html><head></head><body></body></html>
              Fix any of the following:
              - The <html> element does not have a lang attribute

      3) landmark-one-main: Document should have one main landmark (moderate)
          https://dequeuniversity.com/rules/axe/4.2/landmark-one-main?application=axeAPI
          The following 1 node violate this rule:

              Selector: html
              HTML: <html><head></head><body></body></html>
              Fix all of the following:
              - Document does not have a main landmark

      4) page-has-heading-one: Page should contain a level-one heading (moderate)
          https://dequeuniversity.com/rules/axe/4.2/page-has-heading-one?application=axeAPI
          The following 1 node violate this rule:

              Selector: html
              HTML: <html><head></head><body></body></html>
              Fix all of the following:
              - Page must have a level-one heading

      Invocation: axe.run(callback); (RuntimeError)
      C:/Users/DQ_user/Documents/Releases/Axe-core-4.2/axe-core-gems-release-2020-05-06/axe-core-gems-release-2020-05-06/packages/axe-core-api/lib/axe/expectation.rb:4:in `assert'
      C:/Users/DQ_user/Documents/Releases/Axe-core-4.2/axe-core-gems-release-2020-05-06/axe-core-gems-release-2020-05-06/packages/axe-core-cucumber/lib/axe-cucumber.rb:65:in `assert_accessibility'
      features/a11y.feature:11:in `the page should be axe clean'

Failing Scenarios:
cucumber features/a11y.feature:10 # Scenario: Test whole page (known to be inaccessible, should fail)

1 scenario (1 failed)
3 steps (1 failed, 2 passed)
0m13.934s
```

Expected:
```
Violation of "aria-allowed-attr" with 1 occurrences!
    Ensures ARIA attributes are allowed for an element's role. Correct invalid elements at:
     - #wcag2a-fail > a[href="\#"][role="button"]
    For details, see: https://dequeuniversity.com/rules/axe/4.2/aria-allowed-attr

 Violation of "color-contrast" with 1 occurrences!
    Ensures the contrast between foreground and background colors meets WCAG 2 AA contrast ratio thresholds. Correct invalid elements at:
     - #wcag2aa-fail > p
    For details, see: https://dequeuniversity.com/rules/axe/4.2/color-contrast

Violation of "heading-order" with 1 occurrences!
    Ensures the order of headings is semantically correct. Correct invalid elements at:
     - h6
    For details, see: https://dequeuniversity.com/rules/axe/4.2/heading-order

 Violation of "label" with 1 occurrences!
    Ensures every form element has a label. Correct invalid elements at:
     - input[name="lastname"]
    For details, see: https://dequeuniversity.com/rules/axe/4.2/label

4 Accessibility issues detected.
```

Noite:
Watir driver is working fine

**Comment by SantoshDeque** [comment]
Verified in release branch(release-2020-05-17) and issue is fixed. PFA gif file
![20210518_203525](https://user-images.githubusercontent.com/45222788/118676575-25a20380-b819-11eb-8b5a-c1179daf9a93.gif)

**Comment by michael-siek** [comment]
closing no docs required
