### ISSUE TITLE
[axe-core-api] 4.1 -> 4.2 undefined method `switch_to_frame' for #<WebDriverScriptAdapter::FrameAdapter::CapybaraAdapter>

### ISSUE THREAD

**Issue by MadhavanRajarathinam** [dequelabs/axe-core-gems#195]
- Link to live demo (if applicable)

<pre>
<code>
Error:-
    undefined method `switch_to_frame' for # WebDriverScriptAdapter::FrameAdapter::CapybaraAdapter

On callee:-
   within_frame(frame)

Upgrading from 4.1 to 4.2.

dumb_delegator gem still in 0.8.1 version, is that causing the issue?
</code>
</pre>

**Comment by michael-siek** [comment]
Hey @MadhavanRajarathinam  it looks like this has been fixed and released in 4.8.0 https://github.com/dequelabs/axe-core-gems/pull/307 if this is still an issue please feel free to open a new ticket. 

Thank you,

**Comment by padmavemulapati** [comment]
verified with the release-branch code base, issue not there. Its working with the configured browser. 

for chrome config:


https://github.com/dequelabs/axe-core-gems/assets/47409579/e3d23698-8157-4e5c-8954-0746c87b815b

for firefox config:


https://github.com/dequelabs/axe-core-gems/assets/47409579/48f4d0aa-a36f-442d-a9ed-8b60181ce023


` page.visit "http://abcdcomputech.dequecloud.com/"` instead just `visit` would suffice the issue

## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Product**                | _axe-core-gems/rspec-cucumber_ |
|**Version** | _release-2024-02-07_codebase_ |
| **OS-Details**      | _MAC- Intel Core i7 - 11.6.8 && Windows 11 _ |
|**BrowserDetails**|_Chrome Version 121.0.6167.139 && Firefox 122.0.1_|
