### ISSUE TITLE
Can I disable a specific rule *within* a specific selector, using rspec matchers?

### ISSUE THREAD

**Issue by jrochkind** [dequelabs/axe-core-gems#224]
Let's say I have the rule `color-contrast` failing inside `div.some-class`. 

I can't fix this right now for whatever reason, and want to be able to skip it while checking the rest of the page. 

I can say `expect(page).to be_axe_clean.excluding(".some-class")`, and the test will pass again -- but now it's not checking *anything* inside `.some-class`, ideally I'd like it to check other rules, just not `color-contrast`. 

I can say `be_axe_clean.skipping(:"color-contrast")`, but now it's not checking `color-contrast` *anywhere*, ideally I'd like it to check color-contrast in other parts of the page, just not in `div.some-class`. 

Is there any way to tell it to skip a specific rule only inside a specific selector? Can/should there be?

These of course don't work, but one could imagine API like:

```ruby
# not actually existing API, does not work
expect(page).to be_axe_clean.skipping({rule: :"color-contrast", selector: ".some_class"})
expect(page).to be_axe_clean.excluding({selector: ".some-class", rule: :"color-contrast"})
```

**Comment by michael-siek** [comment]
Hi @jrochkind you are correct. Currently the API's do not have the ability to remove a specific rule based on selector/rule, but you do have the ability to modify the results coming out of the API so that you look for a specific selector within the rules and remove it from the results object.

**Comment by jrochkind** [comment]
OK, thanks! I don't understand how to do what you say when operating at the `axe-core-rspec` level. I think this would be a very welcome feature, or else welcome would be instructions for how to implement it yourself by modifying the results coming out of the API.

**Comment by padmavemulapati** [comment]
Associated issue dont have any insights on the feature/enhancement requested, @michael-siek , can you please provide some notes here to validate this ticket

**Comment by padmavemulapati** [comment]
Not Reproducing with exclude api
