### ISSUE TITLE
CI: make sure `.gem` directory is created 

### ISSUE THREAD

**Issue by michael-siek** [dequelabs/axe-core-gems#250]
The `.gem` file is not created so the publishing script fails https://app.circleci.com/pipelines/github/dequelabs/axe-core-gems/413/workflows/5c13141c-5705-4431-bbbb-347bf9ef0a38/jobs/894

**Comment by padmavemulapati** [comment]
@michael-siek , @AdnoC , we are seeing the success build on CircleCI for the canary build pushed , 


![Image](https://user-images.githubusercontent.com/47409579/195392324-4c7e9688-4c18-4df0-829f-3db77d8d356b.png)

 but to do QA , from where we can get canary-build (or) able to fetch. 
for ex: axe-core-npm canary builds we can fetch with `@axe-core/webdriverio@next` , it will give us webdriverio canary build.

**Comment by padmavemulapati** [comment]
as per @michael-siek , devtask
