### ISSUE TITLE
update to use axe-core version 4.4.3

### ISSUE THREAD

**Issue by michael-siek** [dequelabs/axe-core-gems#251]
We should upgrade to use the latest version of axe-core which is axe-core v4.4.3

**Comment by SantoshDeque** [comment]
Verified in latest "Develop" branch, axe-core version has been updated to v4.4.3. PFA screenshot
 
<img width="1389" alt="Screenshot 2022-09-28 at 12 01 32 PM" src="https://user-images.githubusercontent.com/45222788/192706975-c57b8256-c8aa-4066-a792-1b73978834e5.png">
