### ISSUE TITLE
Add new test fixtures for shadow dom selector

### ISSUE THREAD

**Issue by michael-siek** [dequelabs/axe-core-gems#284]
We have added 4 new test for shadow dom selectors for axe-core 4.6 https://github.com/dequelabs/axe-test-fixtures/pull/19 we need to make sure to update and add automated test for shadow dom selectors/new selectors

**Comment by AdnoC** [comment]
https://github.com/dequelabs/axe-core-gems/pull/286

**Comment by SantoshDeque** [comment]
Verified with latest dev branch for labelled iframe and labelled shadow DOM changes and changes are working fine
