### ISSUE TITLE
Update to axe-core4.7

### ISSUE THREAD

**Issue by padmavemulapati** [dequelabs/axe-core-gems#302]
Expected:
All Gems version need update from 4.6.1 - to  4.7.0
Axe-core version need to update from 4.6.0 to 4.7.0

**Comment by SantoshDeque** [comment]
Verified in branch - release-2023-04-19 and in build(4.6.1.pre.81ca285), axe-core is updated to 4.7.0 and all Gems version is updated to 4.7.0
