### ISSUE TITLE
Add frame-tested for unloaded iframes

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core-gems#313]
The [change was made to our javascript APIs](https://github.com/dequelabs/axe-core-npm/pull/752) but needs to be ported to here.

**Comment by padmavemulapati** [comment]
@AdnoC , Is this ticket QA-Required? If yes please add few QA-Notes

**Comment by AdnoC** [comment]
Basic test is that we can scan a page like https://github.com/dequelabs/axe-test-fixtures/blob/v1/fixtures/lazy-loaded-iframe.html and not have it hang. More can be that we get a `frame-tested` for the frame.

**Comment by padmavemulapati** [comment]
Tested the following steps:

1. Created a lazy loaded iframes test file
2.  Ran it using Cucumber and Rspec

To check the violations and incompletes following the `steps.rb`

for `violations`
```
Then('I verify the page has {string} accessibility issues') do |expected_issues_count|
  begin
    results = Axe.run(@driver)
    json_results = results.to_json
    
    # Parse the JSON results
    accessibility_data = JSON.parse(json_results)

    # Count the number of violations
    actual_issues_count = accessibility_data['violations'].length

    expect(actual_issues_count).to eq(expected_issues_count.to_i), "Accessibility issues count mismatch"
  rescue => e
    puts(e.message)
  end
end
```

for `incomplete`

```
Then('I verify the page has {string} accessibility issues') do |expected_issues_count|
  begin
    results = Axe.run(@driver)
    json_results = results.to_json
    
    # Parse the JSON results
    accessibility_data = JSON.parse(json_results)

    # Count the number of incompletes
    actual_issues_count = accessibility_data['incomplete'].length

    expect(actual_issues_count).to eq(expected_issues_count.to_i), "Accessibility issues count mismatch"
  rescue => e
    puts(e.message)
  end
end
```
But we are seeing only for violations results `frame-title`

not for `incomplete` - `frame-tested`

As per @adam - as lazyloaded iframes fix should work for selenium related frameworks, it should work for axe-core-gems both frameworks - cucumber and rspec using all three drivers capybara, watir and selenium.  But not seeing the data for `frame-tested` 
@adam can you please help us to get the data for `incomplete` results

**Comment by padmavemulapati** [comment]
Verified with the latest `axe-core-gems_4.8.2` version, getting `frame-tested` result for lazy loaded iframes.

Test conditions:
1. Lazy loaded iframes:
```/iframes/lazy.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Lazy</title>
  </head>
  <body>
    <h1>Lazy</h1>
    <div style="margin-top: 300vh">
      <iframe id="lazy-iframe" src="https://www.youtube.com/embed/REDRiwmNunA" title="MONTHLY SPOTLIGHT" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy"></iframe>
      <iframe src="baz.html" id="lazy-baz"></iframe>
    </div>
  </body>
</html>
```

```iframefixtures.html
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en" id="lazy-loading-iframe-root">
  <head>
    <title>Lazy Loading Iframe Root</title>
  </head>
  <body>
    <main>
      <h1>iframe context test</h1>
      <div style="margin-top: 300vh">
        <iframe src="iframes/lazy.html" id="ifr-lazy" loading="lazy"></iframe>
      </div>
    </main>
  </body>
</html>
```
Code for rspec-selenium - test.rb

```
require "spec_helper"
require 'axe/core'
require 'axe/api/run'
require "selenium-webdriver"
require "json"

# Typical example using standard RSpec dsl
describe "ABCD CompuTech (RSpec DSL)",
         :type => :feature, :driver => :selenium do
  # before :each do
  #   @driver.page.navigate.to "http://qateam.dequecloud.com/attest/api/test.html"
  # end

  it "prints out version number" do
    @driver.page.navigate.to "http://localhost:8081/iframesfixture.html"
    axe_results = Axe::Core.new(@driver.page).call Axe::API::Run.new
    puts(axe_results.results.testEngine["version"])
    violations = axe_results.results.violations
    violations.each do |violation|
        puts "Rule ID: #{violation.id}" # Print Rule ID for each violation
        puts "Description: #{violation.description}" # Print description of the violation
        # You can access other properties of the violation as needed
    end
    incomplete = axe_results.results.incomplete
    incomplete.each do |incomplete|
    puts "Rule ID: #{incomplete.id}" # Print Rule ID for each violation
    puts "Description: #{incomplete.description}" # Print description of the violation
    # You can access other properties of the violation as needed
  end
end
end
```
Execute: `bundle install` and `bundle exec rspec`

Expectation:
On lazy loaded iframes, page should load and scan successfully. the above mensioned test file get `frame-title` as violation and `frame-tested` as incomplete results.

<img width="872" alt="image" src="https://github.com/dequelabs/axe-core-gems/assets/47409579/da60fd69-17c6-4b60-8e3f-3129ae0a767f">

## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Product**                | _axe-core-gems/rspec-selenium_ |
|**Version** | _4.8.2_ |
| **OS-Details**      | _MAC- Intel Core i7 - 11.6.8 && Windows 11 _ |
|**BrowserDetails**|_Chrome Version 121.0.6167.139 && Firefox 122.0.1_|
