### ISSUE TITLE
undefined method `key?' for nil:NilClass

### ISSUE THREAD

**Issue by asterite** [dequelabs/axe-core-gems#320]
In our CI the `be_axe_clean` matcher is sometimes failing with this error:

```
Failure/Error:
  expect(page).to be_axe_clean.skipping(
    'heading-order',
    'region',
    'page-has-heading-one',
    'landmark-one-main',
    'color-contrast',
  )
NoMethodError:
  undefined method `key?' for nil:NilClass
            if res.key?("errorMessage")
                  ^^^^^
./_build/gems/ruby/3.1.0/gems/axe-core-api-4.7.0/lib/axe/api/run.rb:129:in `run_partial_recursive'
./_build/gems/ruby/3.1.0/gems/axe-core-api-4.7.0/lib/axe/api/run.rb:36:in `analyze_post_43x'
./_build/gems/ruby/3.1.0/gems/axe-core-api-4.7.0/lib/axe/core.rb:18:in `call'
./_build/gems/ruby/3.1.0/gems/axe-core-api-4.7.0/lib/axe/matchers/be_axe_clean.rb:22:in `audit'
./_build/gems/ruby/3.1.0/gems/axe-core-api-4.7.0/lib/axe/matchers/be_axe_clean.rb:26:in `matches?'
./_build/gems/ruby/3.1.0/gems/rspec-expectations-3.11.0/lib/rspec/expectations/handler.rb:51:in `block in handle_matcher'
./_build/gems/ruby/3.1.0/gems/rspec-expectations-3.11.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
./_build/gems/ruby/3.1.0/gems/rspec-expectations-3.11.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
./_build/gems/ruby/3.1.0/gems/rspec-expectations-3.11.0/lib/rspec/expectations/expectation_target.rb:65:in `to'
./_build/gems/ruby/3.1.0/gems/rspec-expectations-3.11.0/lib/rspec/expectations/expectation_target.rb:101:in `to'
```

I can't reliably reproduce this, but... any ideas of why this could be happening? Is it a bug in this library? If so, I'm happy to help and try to fix it.

**Comment by AdnoC** [comment]
I'll look into it

**Comment by AdnoC** [comment]
Interestingly, it seems to be caused by Selenium's `execute_async_script` returning `Nil`. Don't know how since the script we're running always returns a value. Sad that it isn't reproducible, but it can still be mitigated by treating the case as an untested frame.

**Comment by AdnoC** [comment]
This should be fixed now.

**Comment by sameerrawat** [comment]
Working as expected. Hence closing the ticket.
<img width="753" alt="image" src="https://github.com/dequelabs/axe-core-gems/assets/136694520/10c1a8ea-14a5-4179-8485-d2b3ee769c80">
<img width="790" alt="image" src="https://github.com/dequelabs/axe-core-gems/assets/136694520/35994cc2-cb0c-4b48-ba7e-7404b62f4a11">

**Comment by asterite** [comment]
Oh, sorry, I saw this last week but I didn't have time to reply.

Thank you so much for fixing this! ❤️
