### ISSUE TITLE
Pin axe-core version to patch updates only (`~`)

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/axe-core-gems#333]
A user recently ran into a problem where [they installed an api at v4.7](https://github.com/dequelabs/axe-core-npm/issues/830) but got axe-core version v4.8 (causing some confusion on why rules weren't running that should have been). Turns out that we've been pinning to axe-core using `^` which allows minor updates. This goes against our goal of version locking the apis to the major and minor version of axe-core that is used in the api. 

We'll fix this by using `~` to patch pin our axe-core dependency.

**Comment by padmavemulapati** [comment]
Verified with the latest canary build - axe-core-gems_4.7.0.pre.f368a23

As there is no dependency list provided and no package.json created for axe-core-gems, it strictly carry the axe-core version which is updated. 

Now for the v4.7.0.pre.f368a23 , axe-core version is updated to 4.8.2

![image](https://github.com/dequelabs/axe-core-gems/assets/47409579/75ba607d-e8ba-4f2b-ab26-340083fcb953)

for the earlier version - 4.7.0.pre.c204367 , axe-core version was 4.8.1 (So there is no ^ charecter and it is not allowing any minor version without pinning



![image](https://github.com/dequelabs/axe-core-gems/assets/47409579/b0be991c-ad20-4f09-b91b-07b627326ef7)

## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Product**                | _axe-core-gems_|
|**Version** | _4.7.0.pre.f368a23_ |
| **OS-Details**      | _MAC- Intel Core i7 - 11.6.8  & Windows11 _ |
|**BrowserDetails**|_Chrome Version 117.0.5938.88 (Official Build) (64-bit) & Firefox 117.0_|
