### ISSUE TITLE
axe-core-gems v4.8.0 - QA Needed

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/axe-core-gems#336]
Please QA axe-core-gems v4.8.0 release candidate: https://github.com/dequelabs/axe-core-gems/pull/335

**Comment by padmavemulapati** [comment]
@dequejenn and @michael-siek , No issues were observed on the fixes and features of https://github.com/dequelabs/axe-core-gems/pull/335
Done regression testing for all the available API's on both packages - RSpec and Cucumber using three combinations of drivers - watir, capybara, and selenium, everything looking good and seeing the expected results.
Here is the [test plan](https://dequeqa.testrail.io/index.php?/plans/view/2239) , can find the access credentials details in the sign-off e-mail
