### ISSUE TITLE
Set up repo to be able to use dependabot (or similar)

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/axe-core-gems#338]
We need to figure out how to configure dependabot such that it can update the dependancies in that repo; if not possible, how can we change how we reference dependancies so we can use dependabot? If there something easier to use - for example, rennovate - then what is needed to use that instead of dependabot?

To close this ticket, the repo should be ready to accept the dependabot config file (or similar).

**Comment by AdnoC** [comment]
We use `.gemspec`, `Gemfile`, and `Gemfile.lock` files for dependencies, which dependabot supports. So we should be good here.

**Comment by padmavemulapati** [comment]
@AdnoC , is this QA-required?
