### ISSUE TITLE
Ruby throwing Page/Frame not ready exception Safari 

### ISSUE THREAD

**Issue by Zidious** [dequelabs/axe-core-gems#353]
On fast webpages such as google.com I am encountering an intermittent issue when running axe. On slower pages such as https://dequeuniversity.com/demo/mars/ I am not encountering this error. 

Example: 

```ruby
require "selenium-webdriver"
require "axe/api/run"
require "json"

driver = Selenium::WebDriver.for :safari
driver.navigate.to "https://google.com"


res = Axe::Core.new(driver).call Axe::API::Run.new.with_options

puts JSON.pretty_generate res.results.to_h

driver.quit
```

Throws: 

```
➜ ruby ruby_qustion.rb
/usr/local/lib/ruby/gems/3.1.0/gems/axe-core-api-4.8.0/lib/axe/core.rb:51:in `assert_frame_ready': Page/frame not ready (Exception)
	from /usr/local/lib/ruby/gems/3.1.0/gems/axe-core-api-4.8.0/lib/axe/core.rb:56:in `load_axe_core'
	from /usr/local/lib/ruby/gems/3.1.0/gems/axe-core-api-4.8.0/lib/axe/core.rb:14:in `initialize'
	from ruby_qustion.rb:9:in `new'
	from ruby_qustion.rb:9:in `<main>'
```

![image](https://github.com/dequelabs/axe-core-gems/assets/41127686/84b99900-b416-4ff3-891c-8e943674c026)

`NoSuchWindowException` - https://github.com/dequelabs/axe-core-gems/issues/352

**Comment by padmavemulapati** [comment]
Verified with the latest QA-build ( axe-core-gems_4.9.1.pre.396d719) on both Cucumebr and Rspec (which we are supporting now) using seleniium-driver. Not reproducing the issue, its working on safari browsser with out throwing nay error  or exceptions.

Cucumber-selenium:
Driver setup:
```
# load selenium
require "selenium-webdriver"
# require driver of choice
require "axe-selenium"
# Requiring 'axe-cucumber-steps' makes all of the axe-cucumber step
# definitions available to be used directly in your cucumber features.
require "axe-cucumber-steps"

Before do
  # configure AxeSelenium
  @driver = AxeSelenium.configure(:safari) do |c|
  end
end

# close browser when done
After do
  @driver.page.close
end

```
Page executing:

```
Feature: Axe-core-Ruby-Cucumber-Selenium Tests

 Background:
    Given I am a visitor

  Scenario: Test whole page
    When I visit "http://qateam.dequecloud.com/attest/api/test.html"
    Then I verify the page has "8" accessibility issues  
```
Its working as expected.

#### attached recording 


https://github.com/dequelabs/axe-core-gems/assets/47409579/e2f3f778-7e13-4d19-ba0c-133a396cf3a7



Rspec-selenium:
Driver setup:
```
require "rspec"
require "axe-rspec"
require "axe-selenium"

RSpec.configure do |config|
  config.before :each do
    @driver = AxeSelenium.configure(:safari) do |c|
  end    
  end
  config.color = true
end

```
Page executing:

```
require "spec_helper"
require 'axe/core'
require 'axe/api/run'

# Typical example using standard RSpec dsl
describe "TestPage (RSpec DSL)",
         :type => :feature, :driver => :selenium do
 
  it "Test whole page" do
    @driver.page.navigate.to "http://qateam.dequecloud.com/attest/api/test.html"
    axe_results = Axe::Core.new(@driver.page).call Axe::API::Run.new
    puts(axe_results.results.testEngine["version"])
     begin
        expect(@driver.page).to be_axe_clean
        rescue RSpec::Expectations::ExpectationNotMetError => e
        expect("#{e.message}").to include("Found 8 accessibility violation"), "Accessibility issues count mismatch"
     end
  end
```
Its working as expected.

#### attached recording 



https://github.com/dequelabs/axe-core-gems/assets/47409579/5948d885-f150-4d38-82dc-074337c822a6



## Environment:
| **Label**                        | **Value** |
| -------------------------- | ------ |
| **Product**               | _axe-core-gems_ |
|**Version** | _4.9.1.pre.396d719_ |
|**Pacakges**|_Cucumber and RSpec_|
|**Driver**|_Selenium_|
| **OS-Details**     | _MAC- Intel Core i7 - 11.6.8 _ |
|**BrowserDetails**|_Safari Version 17.4.1 (19618.1.15.11.14)_|
