### ISSUE TITLE
Require QA consideration in PRs

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/axe-core-gems#354]
Set up https://github.com/dequelabs/axe-api-team-public/blob/main/.github/actions/semantic-pr-footer-v1 so it will block a PR that does not have at least one of the following:

- There is a link to a valid issue in the description of the PR
- The words "QA NOTES" appear in the description of the PR
- The words "QA NOT NEEDED" appear in the description of the PR

**Comment by padmavemulapati** [comment]
Verified Github actions, work flow is defined for QA-required actions, can find in the below link:

https://github.com/dequelabs/axe-core-gems/blob/4833b41de34ea0dc5c6bb8d298255652b45d4e7e/.github/workflows/semantic-pr-footer.yml#L16

## Screenshot:

<img width="1252" alt="image" src="https://github.com/dequelabs/axe-core-gems/assets/47409579/6cd31fd4-0d5e-4003-b40a-5decb0b6a971">
