### ISSUE TITLE
Create bug report and feature request issue templates in repo

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/axe-core-gems#377]
We need to make sure all information is captured when an issue is created. To doso, we will be utilizing Github Issue Templates 
.
Please create these two issue templates in this repo. They should be copied from our team repo:

- [ ] https://github.com/dequelabs/axe-api-team/blob/main/.github/ISSUE_TEMPLATE/bug-report.md
- [ ] https://github.com/dequelabs/axe-api-team/blob/main/.github/ISSUE_TEMPLATE/feature-request.md

Acceptance Criteria: When a new issue is created, it should show the option of choosing a Bug Report or Feature Request template to start from.

**Comment by padmavemulapati** [comment]
Verified that when we are going to create a new issue it is asking for "Bug Report" / "Feature Request" / "Report a security vulnerability"  templates once we select required one it will gives the relevant template to create an issue



https://github.com/dequelabs/axe-core-gems/assets/47409579/da0cbc7e-7aa6-4e19-b6b1-e93b6488439f
