### ISSUE TITLE
Adding the gem to a Cucumber/Watir project according to the instructions breaks Rake tasks

### ISSUE THREAD

**Issue by jeetshah26** [dequelabs/axe-core-gems#85]
Gem Version-> 2.4.1
Steps to Reproduce
1. Add the gem to the repository Gemfile
2. Add the include to the step definitions `require 'axe/cucumber/step_definitions'` to `features/support/env.rb`
3. Trying to run a rake task after this caused a error when its trying to resolve the require statement in the `env.rb` file

Workaround:
1. Move the `require 'axe/cucumber/step_definitions'`  line to the step definition file that has some of your step definitions for the tests that use this gem

error stack:
`rake aborted!
NoMethodError: undefined method `Then' for main:Object
/usr/local/rvm/gems/ruby-2.5.1@qa_shared_shelf/gems/axe-matchers-2.4.1/lib/axe/cucumber/step_definitions.rb:3:in `<top (required)>'
/Users/jshah/forum-ui/ui_tests/features/support/env.rb:7:in `require'
/Users/jshah/forum-ui/ui_tests/features/support/env.rb:7:in `<top (required)>'
/Users/jshah/forum-ui/ui_tests/Rakefile:4:in `require'
/Users/jshah/forum-ui/ui_tests/Rakefile:4:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.5.1@qa_shared_shelf/gems/rake-12.3.3/lib/rake/rake_module.rb:29:in `load'
/usr/local/rvm/gems/ruby-2.5.1@qa_shared_shelf/gems/rake-12.3.3/lib/rake/rake_module.rb:29:in `load_rakefile'
/usr/local/rvm/gems/ruby-2.5.1@qa_shared_shelf/gems/rake-12.3.3/lib/rake/application.rb:703:in `raw_load_rakefile'
/usr/local/rvm/gems/ruby-2.5.1@qa_shared_shelf/gems/rake-12.3.3/lib/rake/application.rb:104:in `block in load_rakefile'
/usr/local/rvm/gems/ruby-2.5.1@qa_shared_shelf/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.5.1@qa_shared_shelf/gems/rake-12.3.3/lib/rake/application.rb:103:in `load_rakefile'
/usr/local/rvm/gems/ruby-2.5.1@qa_shared_shelf/gems/rake-12.3.3/lib/rake/application.rb:82:in `block in run'
/usr/local/rvm/gems/ruby-2.5.1@qa_shared_shelf/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.5.1@qa_shared_shelf/gems/rake-12.3.3/lib/rake/application.rb:80:in `run'
/usr/local/rvm/gems/ruby-2.5.1@qa_shared_shelf/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.5.1@qa_shared_shelf/bin/rake:23:in `load'
/usr/local/rvm/gems/ruby-2.5.1@qa_shared_shelf/bin/rake:23:in `<main>'`

- Link to live demo (if applicable)

<pre>
<code>
- `axe-matchers` version: X.Y.Z and other relevant notes.
- Browser and Assistive Technology versions (if any).
- Tooling details (if any)
</code>
</pre>

**Comment by jeeyyy** [comment]
@jeetshah26 we have recently refactored and rebranded all of our ruby gems. See [README](https://github.com/dequelabs/axe-core-gems#axe-core-gems) for more details.

We recommend upgrading to the latest version. Please feel free to re-open this ticket if you are having any further issues.
