### ISSUE TITLE
Question: Issues reported from this gem X  chrome extension

### ISSUE THREAD

**Issue by franzejr** [dequelabs/axe-core-gems#86]
Hey everyone,

Thanks for this gem. It's pretty good and It has helped us a lot.

I used this gem in some of the pages from my application and I fixed all the issues, it turns out I discovered this chrome extension: https://chrome.google.com/webstore/detail/axe-web-accessibility-tes/lhdoppojpmngadmnindnejefpokejbdd. When I use the extension it finds other issues that this gem didn't find. 

Should I trust on the chrome extension?

**Comment by jkodu** [comment]
Hi @franzejr 

Thanks for reporting this, would be be able to provide more details on the kind of issues you found with the extension, that the gem did not find? 

We align the results between all of our offerings, but there are scenarios like when testing with the extension perhaps the page was in a different state that when it is tested using the framework consuming the gem. For example may you the site in question was in a responsive layout when using the extension. This could lead to different results.

If the difference in results is an issue given the page state is the same, then feel free to re-open or create a new issue for the same with more details to replicate it. Thank you.
